version: "3.8"

services:

  app1:
    build: .
    container_name: phonestore-app1
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
    restart: always

  app2:
    build: .
    container_name: phonestore-app2
    ports:
      - "3002:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
    restart: always

  app3:
    build: .
    container_name: phonestore-app3
    ports:
      - "3003:3000"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
    restart: always

  nginx:
    image: nginx:alpine
    container_name: phonestore-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: phonestore-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: phonestore-grafana
    ports:
      - "3004:3000"
    depends_on:
      - prometheus
    restart: always

